#spring:
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres123
#    driverClassName: org.postgresql.Driver
